author_id_required = "Please provide author id"
author_not_exists = "Author not exists with provided id"
error_message = "Someting went wrong please try again later"
getting_authors = "List of available authors"
author_added = "Author data saved successfully"
author_data = "Author data fetched successfully"
author_updated = "Author data updated successfully"
author_deleted = "Author data deleted successfully"

book_not_exists = "Book not exists with provided id"
getting_books = "List of available books"
book_added = "Book data saved successfully"
book_data = "Book data fetched successfully"
book_updated = "Book data updated successfully"
book_deleted = "Book data deleted successfully"
